#!/bin/bash
# ============================================================
# 👑 King OS Repository Builder (Fully Automated)
# ============================================================

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$REPO_ROOT/config/repo.conf"

# Load config
if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Config not found. Run ./setup.sh first."
    exit 1
fi
source "$CONFIG_FILE"

FIND_URL="$REPO_ROOT/scraper/find-package-url.sh"
SOURCES_FILE="$REPO_ROOT/sources.txt"
METADATA_DIR="$TEMP_DIR/metadata"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

# ============================================================
# INIT
# ============================================================
mkdir -p "$PACKAGES_DIR"
mkdir -p "$TEMP_DIR"

echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo -e "${PURPLE}  👑 King OS Repository Builder${NC}"
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo ""

# Prerequisites
for tool in python3 wget ar tar zstd git curl; do
    if ! command -v $tool &> /dev/null; then
        echo -e "${RED}❌ Missing: $tool${NC}"
        exit 1
    fi
done

# Read packages
if [ ! -f "$PACKAGES_LIST" ]; then
    echo -e "${RED}❌ packages.txt not found${NC}"
    exit 1
fi

PACKAGES=()
while IFS= read -r line; do
    [[ "$line" =~ ^#.*$ ]] && continue
    [[ -z "$line" ]] && continue
    PACKAGES+=("$(echo "$line" | tr -d '[:space:]')")
done < "$PACKAGES_LIST"

echo -e "${CYAN}📦 Found ${#PACKAGES[@]} packages to process${NC}"
echo ""

if [ ${#PACKAGES[@]} -eq 0 ]; then
    echo -e "${YELLOW}⚠️  No packages in packages.txt${NC}"
    exit 0
fi

# Load index
if [ ! -f "$INDEX_FILE" ]; then
    echo '{"version":"1.0","generated":"","packages":{}}' > "$INDEX_FILE"
fi

# Clear sources.txt and rebuild it
echo "# Auto-generated by king-repo-build.sh on $(date)" > "$SOURCES_FILE"

# ============================================================
# PROCESS EACH PACKAGE
# ============================================================
UPDATED=0
SKIPPED=0
FAILED=0
UPDATED_PACKAGES=()
DELETED_PACKAGES=()

for PKG in "${PACKAGES[@]}"; do
    echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}🔷 $PKG${NC}"
    echo ""
    
    # Find URL
    echo -e "${BLUE}   🔍 Searching...${NC}"
    URL=$("$FIND_URL" "$PKG" "$UBUNTU_SUITE" 2>/dev/null || echo "NOT_FOUND")
    
    if [ "$URL" = "NOT_FOUND" ] || [ -z "$URL" ]; then
        echo -e "${RED}   ❌ Not found in Ubuntu repos${NC}"
        FAILED=$((FAILED + 1))
        continue
    fi
    
    echo -e "${GREEN}   ✅ Found: $(basename "$URL")${NC}"
    
    # Log to sources.txt
    echo "$URL" >> "$SOURCES_FILE"
    
    FILENAME=$(basename "$URL")
    DOWNLOAD_PATH="$TEMP_DIR/$FILENAME"
    
    # Download
    echo -e "${BLUE}   ⬇️  Downloading...${NC}"
    if ! wget -q --show-progress -O "$DOWNLOAD_PATH" "$URL"; then
        echo -e "${RED}   ❌ Download failed${NC}"
        FAILED=$((FAILED + 1))
        continue
    fi
    echo -e "${GREEN}   ✅ Downloaded${NC}"
    
    # Extract metadata
    rm -rf "$METADATA_DIR"
    mkdir -p "$METADATA_DIR"
    
    cd "$METADATA_DIR"
    ar x "$DOWNLOAD_PATH" 2>/dev/null
    
    CONTROL_ARCHIVE=""
    for f in control.tar*; do
        [ -f "$f" ] && CONTROL_ARCHIVE="$f" && break
    done
    
    if [ -z "$CONTROL_ARCHIVE" ]; then
        echo -e "${RED}   ❌ No control file${NC}"
        FAILED=$((FAILED + 1))
        cd "$REPO_ROOT"
        continue
    fi
    
    case "$CONTROL_ARCHIVE" in
        *.gz) tar -xzf "$CONTROL_ARCHIVE" ;;
        *.xz) tar -xJf "$CONTROL_ARCHIVE" ;;
        *.zst) tar --use-compress-program=unzstd -xf "$CONTROL_ARCHIVE" ;;
        *) tar -xf "$CONTROL_ARCHIVE" ;;
    esac
    
    PKG_NAME=$(grep "^Package:" control | cut -d' ' -f2- | tr -d '\r')
    PKG_VERSION=$(grep "^Version:" control | cut -d' ' -f2- | tr -d '\r')
    PKG_ARCH=$(grep "^Architecture:" control | cut -d' ' -f2- | tr -d '\r')
    PKG_DEPENDS_RAW=$(grep "^Depends:" control | cut -d' ' -f2- | tr -d '\r' || echo "")
    PKG_DESC=$(grep "^Description:" control | cut -d' ' -f2- | tr -d '\r' | head -1)
    
    PKG_DEPENDS=""
    if [ -n "$PKG_DEPENDS_RAW" ]; then
        PKG_DEPENDS=$(echo "$PKG_DEPENDS_RAW" | sed 's/([^)]*)//g' | sed 's/, */,/g' | sed 's/ *$//')
    fi
    
    cd "$REPO_ROOT"
    
    echo -e "${GREEN}   📋 Version: $PKG_VERSION${NC}"
    echo -e "${GREEN}   📋 Depends: ${PKG_DEPENDS:-none}${NC}"
    
    # Check existing
    OLD_VERSION=$(python3 -c "
import json
try:
    with open('$INDEX_FILE') as f:
        data = json.load(f)
    pkg = data.get('packages', {}).get('$PKG_NAME')
    if pkg:
        print(pkg.get('version', ''))
except:
    pass
")
    
    if [ "$OLD_VERSION" = "$PKG_VERSION" ]; then
        echo -e "${YELLOW}   ⏭️  Same version — skipping${NC}"
        SKIPPED=$((SKIPPED + 1))
        rm -f "$DOWNLOAD_PATH"
        continue
    fi
    
    # Delete old versions
    if [ -n "$OLD_VERSION" ]; then
        echo -e "${YELLOW}   🔄 Old: $OLD_VERSION → New: $PKG_VERSION${NC}"
        find "$PACKAGES_DIR" -name "${PKG_NAME}-*-${PKG_ARCH}.kpk" -type f -delete
        DELETED_PACKAGES+=("$PKG_NAME ($OLD_VERSION)")
    fi
    
    # Convert to .kpk
    EXTRACT_DIR="$TEMP_DIR/build-$PKG_NAME"
    rm -rf "$EXTRACT_DIR"
    mkdir -p "$EXTRACT_DIR"
    
    cp "$DOWNLOAD_PATH" "$EXTRACT_DIR/"
    cd "$EXTRACT_DIR"
    ar x "$(basename "$DOWNLOAD_PATH")"
    
    for data_file in data.tar*; do
        [ -f "$data_file" ] || continue
        case "$data_file" in
            *.gz) tar -xzf "$data_file" ;;
            *.xz) tar -xJf "$data_file" ;;
            *.zst) tar --use-compress-program=unzstd -xf "$data_file" ;;
            *) tar -xf "$data_file" ;;
        esac
        rm -f "$data_file"
    done
    
    rm -f control.tar* debian-binary
    
    cat > manifest.json << MEOF
{
  "name": "$PKG_NAME",
  "version": "$PKG_VERSION",
  "arch": "$PKG_ARCH",
  "built_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
MEOF
    
    KPK_FILENAME="${PKG_NAME}-${PKG_VERSION}-${PKG_ARCH}.kpk"
    KPK_PATH="$PACKAGES_DIR/$KPK_FILENAME"
    
    tar --use-compress-program=zstd -cf "$KPK_PATH" -C "$EXTRACT_DIR" .
    
    KPK_SIZE=$(stat -c%s "$KPK_PATH")
    KPK_SHA256=$(sha256sum "$KPK_PATH" | cut -d' ' -f1)
    
    echo -e "${GREEN}   ✅ Created: $KPK_FILENAME${NC}"
    echo -e "${GREEN}   ✅ Size: $(numfmt --to=iec $KPK_SIZE)${NC}"
    
    # Update index
    python3 << PYEOF
import json
from datetime import datetime, UTC

with open('$INDEX_FILE', 'r') as f:
    index = json.load(f)

if 'packages' not in index:
    index['packages'] = {}

index['packages']['$PKG_NAME'] = {
    'version': '$PKG_VERSION',
    'arch': '$PKG_ARCH',
    'filename': 'packages/$KPK_FILENAME',
    'sha256': '$KPK_SHA256',
    'size': $KPK_SIZE,
    'depends': [d for d in '$PKG_DEPENDS'.split(',') if d],
    'description': '''$PKG_DESC''',
    'date_added': datetime.now(UTC).strftime('%Y-%m-%d'),
    'reboot_required': False,
}

index['generated'] = datetime.now(UTC).isoformat()

with open('$INDEX_FILE', 'w') as f:
    json.dump(index, f, indent=2)
PYEOF
    
    echo -e "${GREEN}   ✅ Index updated${NC}"
    echo ""
    
    UPDATED=$((UPDATED + 1))
    UPDATED_PACKAGES+=("$PKG_NAME → $PKG_VERSION")
    
    rm -rf "$EXTRACT_DIR"
    rm -f "$DOWNLOAD_PATH"
    rm -rf "$METADATA_DIR"
done

# ============================================================
# SUMMARY
# ============================================================
echo ""
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo -e "${PURPLE}  📊 Build Summary${NC}"
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}   ✅ Updated:  $UPDATED${NC}"
echo -e "${YELLOW}   ⏭️  Skipped:  $SKIPPED${NC}"
echo -e "${RED}   ❌ Failed:   $FAILED${NC}"
echo ""

if [ ${#UPDATED_PACKAGES[@]} -gt 0 ]; then
    echo -e "${CYAN}   Updated:${NC}"
    for pkg in "${UPDATED_PACKAGES[@]}"; do
        echo -e "${CYAN}     • $pkg${NC}"
    done
    echo ""
fi

if [ ${#DELETED_PACKAGES[@]} -gt 0 ]; then
    echo -e "${YELLOW}   Deleted old versions:${NC}"
    for pkg in "${DELETED_PACKAGES[@]}"; do
        echo -e "${YELLOW}     • $pkg${NC}"
    done
    echo ""
fi

# ============================================================
# SAFE AUTO-SYNC + PUSH
# ============================================================
if [ $UPDATED -gt 0 ]; then
    echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
    echo -e "${PURPLE}  🚀 Auto-Sync to GitHub${NC}"
    echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
    echo ""
    
    cd "$REPO_ROOT"
    
    # Init git if needed
    if [ ! -d ".git" ]; then
        git init
        git branch -M main
        git remote add origin "$GIT_URL"
    fi
    
    # Ensure remote set
    if ! git remote get-url origin >/dev/null 2>&1; then
        git remote add origin "$GIT_URL"
    fi
    
    # Stage
    git add -A
    
    # Commit
    git commit -m "Auto-update: $UPDATED packages ($(date +%Y-%m-%d))" || true
    
    # Safe fetch + merge (NO FORCE)
    echo -e "${BLUE}   🔄 Syncing with remote...${NC}"
    git fetch origin "$GIT_BRANCH" 2>/dev/null || true
    
    if git rev-parse --verify "origin/$GIT_BRANCH" >/dev/null 2>&1; then
        # Try to merge remote (safe)
        if ! git merge "origin/$GIT_BRANCH" --allow-unrelated-histories --no-edit -m "Auto-merge" 2>/dev/null; then
            echo -e "${YELLOW}   ⚠️  Merge conflict — resolving (keeping local files)${NC}"
            git merge --abort 2>/dev/null || true
            git checkout --ours . 2>/dev/null || true
            git add -A
            git commit -m "Resolved conflicts (kept local)" 2>/dev/null || true
        fi
    fi
    
    # Push
    echo -e "${BLUE}   📤 Pushing...${NC}"
    git push --set-upstream origin "$GIT_BRANCH" 2>&1 | tail -3 || {
        echo -e "${YELLOW}   ⚠️  Push failed — trying pull+push${NC}"
        git pull origin "$GIT_BRANCH" --no-rebase --no-edit 2>/dev/null || true
        git push origin "$GIT_BRANCH" 2>&1 | tail -3
    }
    
    echo ""
    echo -e "${GREEN}   ✅ Pushed to GitHub${NC}"
fi

# ============================================================
# CLEANUP
# ============================================================
rm -rf "$TEMP_DIR"

echo ""
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ King OS Repo Build Complete!${NC}"
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo ""

