#!/bin/bash
# ============================================================
# 👑 King OS Repository Builder (Automated + Rollback Support)
# ============================================================

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$REPO_ROOT/config/repo.conf"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Config not found. Run ./setup.sh first."
    exit 1
fi
source "$CONFIG_FILE"

SOURCES_FILE="$REPO_ROOT/sources.txt"
FIND_URL="$REPO_ROOT/scraper/find-package-url.sh"
METADATA_DIR="$TEMP_DIR/metadata"

# Maximum versions to keep per package (current + previous)
KEEP_VERSIONS=3

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

# ============================================================
# INIT
# ============================================================
mkdir -p "$PACKAGES_DIR"
mkdir -p "$TEMP_DIR"

echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo -e "${PURPLE}  👑 King OS Repository Builder${NC}"
echo -e "${PURPLE}  (Rollback Support: Keep $KEEP_VERSIONS versions)${NC}"
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo ""

# Prerequisites
for tool in python3 wget ar tar zstd git curl; do
    if ! command -v $tool &> /dev/null; then
        echo -e "${RED}❌ Missing: $tool${NC}"
        exit 1
    fi
done

if [ ! -f "$PACKAGES_LIST" ]; then
    echo -e "${RED}❌ packages.txt not found${NC}"
    exit 1
fi

PACKAGES=()
while IFS= read -r line; do
    [[ "$line" =~ ^#.*$ ]] && continue
    [[ -z "$line" ]] && continue
    PACKAGES+=("$(echo "$line" | tr -d '[:space:]')")
done < "$PACKAGES_LIST"

echo -e "${CYAN}📦 Found ${#PACKAGES[@]} packages to process${NC}"
echo -e "${CYAN}📚 Keeping $KEEP_VERSIONS versions per package${NC}"
echo ""

if [ ${#PACKAGES[@]} -eq 0 ]; then
    echo -e "${YELLOW}⚠️  No packages in packages.txt${NC}"
    exit 0
fi

# Load index
if [ ! -f "$INDEX_FILE" ]; then
    echo '{"version":"1.0","generated":"","packages":{}}' > "$INDEX_FILE"
fi

# Clear sources
echo "# Auto-generated by king-repo-build.sh on $(date)" > "$SOURCES_FILE"

# ============================================================
# PROCESS EACH PACKAGE
# ============================================================
UPDATED=0
SKIPPED=0
FAILED=0
ARCHIVED=0
UPDATED_PACKAGES=()

for PKG in "${PACKAGES[@]}"; do
    echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}🔷 $PKG${NC}"
    echo ""
    
    # Find URL
    echo -e "${BLUE}   🔍 Searching...${NC}"
    URL=$("$FIND_URL" "$PKG" "$UBUNTU_SUITE" 2>/dev/null || echo "NOT_FOUND")
    
    if [ "$URL" = "NOT_FOUND" ] || [ -z "$URL" ]; then
        echo -e "${RED}   ❌ Not found${NC}"
        FAILED=$((FAILED + 1))
        continue
    fi
    
    echo -e "${GREEN}   ✅ Found: $(basename "$URL")${NC}"
    echo "$URL" >> "$SOURCES_FILE"
    
    FILENAME=$(basename "$URL")
    DOWNLOAD_PATH="$TEMP_DIR/$FILENAME"
    
    # Download
    echo -e "${BLUE}   ⬇️  Downloading...${NC}"
    if ! wget -q --show-progress -O "$DOWNLOAD_PATH" "$URL"; then
        echo -e "${RED}   ❌ Download failed${NC}"
        FAILED=$((FAILED + 1))
        continue
    fi
    echo -e "${GREEN}   ✅ Downloaded${NC}"
    
    # Extract metadata
    rm -rf "$METADATA_DIR"
    mkdir -p "$METADATA_DIR"
    cd "$METADATA_DIR"
    ar x "$DOWNLOAD_PATH" 2>/dev/null
    
    CONTROL_ARCHIVE=""
    for f in control.tar*; do
        [ -f "$f" ] && CONTROL_ARCHIVE="$f" && break
    done
    
    if [ -z "$CONTROL_ARCHIVE" ]; then
        echo -e "${RED}   ❌ No control file${NC}"
        FAILED=$((FAILED + 1))
        cd "$REPO_ROOT"
        continue
    fi
    
    case "$CONTROL_ARCHIVE" in
        *.gz) tar -xzf "$CONTROL_ARCHIVE" ;;
        *.xz) tar -xJf "$CONTROL_ARCHIVE" ;;
        *.zst) tar --use-compress-program=unzstd -xf "$CONTROL_ARCHIVE" ;;
        *) tar -xf "$CONTROL_ARCHIVE" ;;
    esac
    
    PKG_NAME=$(grep "^Package:" control | cut -d' ' -f2- | tr -d '\r')
    PKG_VERSION=$(grep "^Version:" control | cut -d' ' -f2- | tr -d '\r')
    PKG_ARCH=$(grep "^Architecture:" control | cut -d' ' -f2- | tr -d '\r')
    PKG_DEPENDS_RAW=$(grep "^Depends:" control | cut -d' ' -f2- | tr -d '\r' || echo "")
    PKG_DESC=$(grep "^Description:" control | cut -d' ' -f2- | tr -d '\r' | head -1)
    
    PKG_DEPENDS=""
    if [ -n "$PKG_DEPENDS_RAW" ]; then
        PKG_DEPENDS=$(echo "$PKG_DEPENDS_RAW" | sed 's/([^)]*)//g' | sed 's/, */,/g' | sed 's/ *$//')
    fi
    
    cd "$REPO_ROOT"
    
    # Create package subfolder
    PKG_DIR="$PACKAGES_DIR/$PKG_NAME"
    mkdir -p "$PKG_DIR"
    
    echo -e "${GREEN}   📋 Version: $PKG_VERSION${NC}"
    echo -e "${GREEN}   📋 Depends: ${PKG_DEPENDS:-none}${NC}"
    
    # Check current version
    CURRENT_VERSION=$(python3 -c "
import json
try:
    with open('$INDEX_FILE') as f:
        data = json.load(f)
    pkg = data.get('packages', {}).get('$PKG_NAME')
    if pkg:
        print(pkg.get('current', ''))
except:
    pass
")
    
    if [ "$CURRENT_VERSION" = "$PKG_VERSION" ]; then
        echo -e "${YELLOW}   ⏭️  Current version — skipping${NC}"
        SKIPPED=$((SKIPPED + 1))
        rm -f "$DOWNLOAD_PATH"
        continue
    fi
    
    echo -e "${YELLOW}   🔄 Current: ${CURRENT_VERSION:-none} → New: $PKG_VERSION${NC}"
    
    # Convert to .kpk
    EXTRACT_DIR="$TEMP_DIR/build-$PKG_NAME"
    rm -rf "$EXTRACT_DIR"
    mkdir -p "$EXTRACT_DIR"
    
    cp "$DOWNLOAD_PATH" "$EXTRACT_DIR/"
    cd "$EXTRACT_DIR"
    ar x "$(basename "$DOWNLOAD_PATH")"
    
    for data_file in data.tar*; do
        [ -f "$data_file" ] || continue
        case "$data_file" in
            *.gz) tar -xzf "$data_file" ;;
            *.xz) tar -xJf "$data_file" ;;
            *.zst) tar --use-compress-program=unzstd -xf "$data_file" ;;
            *) tar -xf "$data_file" ;;
        esac
        rm -f "$data_file"
    done
    
    rm -f control.tar* debian-binary
    
    cat > manifest.json << MEOF
{
  "name": "$PKG_NAME",
  "version": "$PKG_VERSION",
  "arch": "$PKG_ARCH",
  "built_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
MEOF
    
    KPK_FILENAME="${PKG_NAME}-${PKG_VERSION}-${PKG_ARCH}.kpk"
    KPK_PATH="$PKG_DIR/$KPK_FILENAME"
    
    tar --use-compress-program=zstd -cf "$KPK_PATH" -C "$EXTRACT_DIR" .
    
    KPK_SIZE=$(stat -c%s "$KPK_PATH")
    KPK_SHA256=$(sha256sum "$KPK_PATH" | cut -d' ' -f1)
    
    echo -e "${GREEN}   ✅ Created: $KPK_FILENAME${NC}"
    echo -e "${GREEN}   ✅ Size: $(numfmt --to=iec $KPK_SIZE)${NC}"
    
    # ============================================================
    # ARCHIVE OLD VERSIONS (keep only KEEP_VERSIONS)
    # ============================================================
    VERSIONS=$(find "$PKG_DIR" -name "${PKG_NAME}-*-${PKG_ARCH}.kpk" -type f | sort -V)
    VERSION_COUNT=$(echo "$VERSIONS" | wc -l)
    
    if [ "$VERSION_COUNT" -gt "$KEEP_VERSIONS" ]; then
        # Delete oldest versions (keep newest KEEP_VERSIONS)
        TO_DELETE=$(echo "$VERSIONS" | head -n -"$KEEP_VERSIONS")
        
        echo -e "${YELLOW}   📦 Keeping latest $KEEP_VERSIONS versions${NC}"
        echo -e "${YELLOW}   🗑️  Archiving older versions...${NC}"
        
        while IFS= read -r old_kpk; do
            [ -f "$old_kpk" ] || continue
            echo -e "${YELLOW}      Archiving: $(basename "$old_kpk")${NC}"
            rm -f "$old_kpk"
            ARCHIVED=$((ARCHIVED + 1))
        done <<< "$TO_DELETE"
    fi
    
    # ============================================================
    # UPDATE INDEX.JSON WITH ALL VERSIONS
    # ============================================================
    python3 << PYEOF
import json
from datetime import datetime, UTC
import glob
import os
import hashlib

with open('$INDEX_FILE', 'r') as f:
    index = json.load(f)

if 'packages' not in index:
    index['packages'] = {}

# Gather all versions currently in package folder
available = []
for kpk in sorted(glob.glob("$PKG_DIR/${PKG_NAME}-*-${PKG_ARCH}.kpk")):
    # Extract version from filename
    basename = os.path.basename(kpk)
    ver = basename.replace("${PKG_NAME}-", "").replace("-${PKG_ARCH}.kpk", "")
    
    # Compute SHA256
    h = hashlib.sha256()
    with open(kpk, 'rb') as f:
        for chunk in iter(lambda: f.read(4096), b''):
            h.update(chunk)
    sha = h.hexdigest()
    
    size = os.path.getsize(kpk)
    
    available.append({
        'version': ver,
        'filename': f"packages/${PKG_NAME}/{basename}",
        'sha256': sha,
        'size': size,
        'date_added': datetime.now(UTC).strftime('%Y-%m-%d'),
        'stable': True,
    })

# Sort by version (newest first)
available.sort(key=lambda x: x['version'], reverse=True)

index['packages']['$PKG_NAME'] = {
    'current': '$PKG_VERSION',
    'arch': '$PKG_ARCH',
    'depends': [d for d in '$PKG_DEPENDS'.split(',') if d],
    'description': '''$PKG_DESC''',
    'available_versions': available,
}

index['generated'] = datetime.now(UTC).isoformat()

with open('$INDEX_FILE', 'w') as f:
    json.dump(index, f, indent=2)
PYEOF
    
    echo -e "${GREEN}   ✅ Index updated${NC}"
    echo ""
    
    UPDATED=$((UPDATED + 1))
    UPDATED_PACKAGES+=("$PKG_NAME → $PKG_VERSION")
    
    rm -rf "$EXTRACT_DIR"
    rm -f "$DOWNLOAD_PATH"
    rm -rf "$METADATA_DIR"
done

# ============================================================
# SUMMARY
# ============================================================
echo ""
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo -e "${PURPLE}  📊 Build Summary${NC}"
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}   ✅ Updated:  $UPDATED${NC}"
echo -e "${YELLOW}   ⏭️  Skipped:  $SKIPPED${NC}"
echo -e "${RED}   ❌ Failed:   $FAILED${NC}"
echo -e "${CYAN}   📦 Archived: $ARCHIVED${NC}"
echo ""

if [ ${#UPDATED_PACKAGES[@]} -gt 0 ]; then
    echo -e "${CYAN}   Updated packages:${NC}"
    for pkg in "${UPDATED_PACKAGES[@]}"; do
        echo -e "${CYAN}     • $pkg${NC}"
    done
    echo ""
fi

# ============================================================
# SAFE AUTO-SYNC + PUSH
# ============================================================
if [ $UPDATED -gt 0 ]; then
    echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
    echo -e "${PURPLE}  🚀 Auto-Sync to GitHub${NC}"
    echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
    echo ""
    
    cd "$REPO_ROOT"
    
    if [ ! -d ".git" ]; then
        git init
        git branch -M main
        git remote add origin "$GIT_URL"
    fi
    
    if ! git remote get-url origin >/dev/null 2>&1; then
        git remote add origin "$GIT_URL"
    fi
    
    git add -A
    git commit -m "Auto-update: $UPDATED packages + rollback support ($(date +%Y-%m-%d))" || true
    
    echo -e "${BLUE}   🔄 Syncing with remote...${NC}"
    git fetch origin "$GIT_BRANCH" 2>/dev/null || true
    
    if git rev-parse --verify "origin/$GIT_BRANCH" >/dev/null 2>&1; then
        if ! git merge "origin/$GIT_BRANCH" --allow-unrelated-histories --no-edit -m "Auto-merge" 2>/dev/null; then
            echo -e "${YELLOW}   ⚠️  Merge conflict — resolving (keeping local)${NC}"
            git merge --abort 2>/dev/null || true
            git checkout --ours . 2>/dev/null || true
            git add -A
            git commit -m "Resolved conflicts (kept local)" 2>/dev/null || true
        fi
    fi
    
    echo -e "${BLUE}   📤 Pushing...${NC}"
    git push --set-upstream origin "$GIT_BRANCH" 2>&1 | tail -3 || {
        echo -e "${YELLOW}   ⚠️  Push failed — trying pull+push${NC}"
        git pull origin "$GIT_BRANCH" --no-rebase --no-edit 2>/dev/null || true
        git push origin "$GIT_BRANCH" 2>&1 | tail -3
    }
    
    echo ""
    echo -e "${GREEN}   ✅ Pushed to GitHub${NC}"
fi

rm -rf "$TEMP_DIR"

echo ""
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ King OS Repo Build Complete!${NC}"
echo -e "${PURPLE}════════════════════════════════════════════════════════${NC}"
echo ""

